### ISSUE TITLE
Operators :< and @

### ISSUE THREAD

**Issue by brucou** [Fuco1/haskell#1]
Not really an issue, but I could not find with googling what were the operators `:<` and `@` standing for. Could you quickly explain their semantics? 

Thanks!

**Comment by Fuco1** [comment]
The `:<` operator is defined in the comonad source file and is defined as

```haskell
data Iterator a = a :< (Iterator a) deriving Eq
infixr 5 :<
```

You can think of it as an inline data constructor similar to `:`.  The above code could we written something like

```haskell
data Iterator a = ICons a (Iterator a) deriving Eq
```

Then you would construct things with `ICons` and not `:<`, so 

```haskell
instance Functor Iterator where
  fmap f (a :< it) = (f a) :< (fmap f it)
```

would become

```haskell  
instance Functor Iterator where
  fmap f (ICons a it) = ICons (f a) (fmap f it)
```


Here is an analogy for the ordinary list:

```haskell
-- this is built-in in haskell
data [a] = a : [a] | []
infixr 5 :

data List a = Cons a (List a) | Empty
```

Here is an explanation of why it is called `Cons` https://en.wikipedia.org/wiki/Cons

The `@` is built-in haskell operator to bind substructures: https://stackoverflow.com/questions/30326249/what-does-mean-in-haskell

It allows you to name the whole expression and patternmatch at the same time.

**Comment by brucou** [comment]
Out of curiosity, how would you define a `filter` operator?, i.e `filter :: filterFn -> Iterator a -> Iterator a`? I could not manage to do it, except defining a new `zero` value, meaning that there is actually no value returned by the next. So in fact `filter :: filterFn -> Iterator a -> Maybe Iterator a`. But then that forces me to lift every `Iterator a` into a `Maybe Iterator a`. 
My goal is to define operators on Iterators, the same way we have operators on streams, i.e. map, filter, foldl, etc.
Is there any other way? This is not comonad transformers because Maybe is a monad, but Iterator is a comonad...

**Comment by Fuco1** [comment]
I suppose just a "regular" filter would work

```haskell
filterC :: (a -> Bool) -> Iterator a -> Iterator a
filterC f (a :< as) = if f a then a :< (filterC f as) else filterC f as
```

This should be quite similar to the list variant except ignoring the empty list case.
